# примеры API-запросов

@baseUrl = http://127.0.0.1:8000/api

# получение объявлений
GET {{baseUrl}}/advertisements/
# Authorization: Token 8f371f0d22debda26dc60ddab827ab532b08ac39
# Content-Type: application/json

###

# создание объявления
POST {{baseUrl}}/advertisements/
Content-Type: application/json
Authorization: Token 8f371f0d22debda26dc60ddab827ab532b08ac39

{
  "title": "стул",
  "description": "старый"
}

###

# попытка поменять объявление
PATCH {{baseUrl}}/advertisements/13/
Content-Type: application/json
Authorization: Token 8f371f0d22debda26dc60ddab827ab532b08ac39

{
  "status": "CLOSED"
}

###

# фильтрация по создателю
GET {{baseUrl}}/advertisements/?creator=2
Content-Type: application/json

###

# фильтрация по дате
GET {{baseUrl}}/advertisements/?created_at_before=2025-07-26
Content-Type: application/json

###
DELETE {{baseUrl}}/advertisements/12/
Authorization: Token 8f371f0d22debda26dc60ddab827ab532b08ac39